services:
  # ----------neo4j----------
  neo4j:
    container_name: neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    image: ${NEO4J_IMAGE}
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    restart: ${RESTART_MODE}
    volumes:
      - ./neo4j_data:/neo4j/data
      - ./neo4j_conf:/neo4j/conf
      - ./neo4j_logs:/neo4j/logs
      - ./neo4j_plugins:/neo4j/plugins
# --volumes-------------------
volumes:
  neo4j_data:
  neo4j_conf:
  neo4j_logs:
  neo4j_plugins: