services:
  neo4j:
    container_name: neo4j
    image: neo4j:5.26.8-community
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
      - "7473:7473" # HTTPS
    restart: unless-stopped
    volumes:
      - neo4j_data:/data
      - neo4j_conf:/conf
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_conf:
  neo4j_logs:
  neo4j_plugins:
