version: "3.9"
services:
  postgres:
    container_name: PostgreSQL
    environment:
      - POSTGRES_USER=${DEFAULT_USERNAME}
      - POSTGRES_PASSWORD=${DEFAULT_PASSWORD}
      - PGDATA=/postgres/data
    image: ${POSTGRES_IMAGE}
    ports:
      - "5432:5432"
    restart: ${RESTART_MODE}
    volumes:
      - ./postgres_data:/postgres/data

  sonarqube:
    container_name: SonarQube
    image: ${SONARQUBE_IMAGE}
    ports:
      - "9002:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/${DEFAULT_DB}
      SONAR_JDBC_USERNAME: ${DEFAULT_USERNAME}
      SONAR_JDBC_PASSWORD: ${DEFAULT_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: ${RESTART_MODE}

volumes:
  postgres_data:
    external: true
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
