services:
  mongodb:
    container_name: mongodb
    # environment:
    #   - MONGO_DATA_DIR=${MONGO_DATA_DIR}
    #   - MONGO_LOG_DIR=${MONGO_LOG_DIR}
    image: mongo:5.0.9
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./mongo-data:/data/db
    # networks:
    #   - network
    # consumer:
    #   build: consumer

  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: postgres:14.3
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres_data:/data/db
    # networks:
    #   - network
    # consumer:
    #   build: consumer

  rabbitmq:
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    image: rabbitmq:3.10.5-management
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    # volumes:
    # - ./rabbitmq-data:/data/db
    # networks:
    #   - network
    # consumer:
    #   build: consumer

  redis:
    container_name: redis
    # environment:
    #   RABBITMQ_DEFAULT_USER: username
    #   RABBITMQ_DEFAULT_PASS: password
    image: redis:7.0.2
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./redis-data:/data/db
    # networks:
    #   - network
    # consumer:
    #   build: consumer
