services:
  # ----------mysql----------
  mysql:
    container_name: mysql
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_USER=${DEFAULT_USERNAME}
      - MYSQL_PASS=${DEFAULT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
    image: ${MYSQL_IMAGE}
    ports:
      - "3306:3306"
      - "33060:33060"
    restart: ${RESTART_MODE}
    volumes:
      - ./mysql_data:/var/lib/mysql
  # ----------postgres----------
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=${DEFAULT_USERNAME}
      - POSTGRES_PASSWORD=${DEFAULT_PASSWORD}
      - PGDATA=/postgres/data
    image: ${POSTGRES_IMAGE}
    ports:
      - "5432:5432"
    restart: ${RESTART_MODE}
    volumes:
      - ./postgres_data:/postgres/data
# --volumes-------------------
volumes:
  mysql_data:
    external: true
  postgres_data:
    external: true