services:
  consul:
    container_name: Consul
    image: hashicorp/consul:1.20.4
    ports:
      - "8500:8500"
      - "8600:8600"
    restart: unless-stopped
  # Uncomment the following lines if custom configurations or certificates are required
  # environment:
  #   - CONSUL_BIND_INTERFACE=eth0
  # volumes:
  #   - ./server1.json:/consul/config/server1.json:ro
  #   - ./certs/:/consul/config/certs/:ro

  # Uncomment this section if a custom network is required
  # networks:
  #   consul:
  #     driver: bridge
