version: "3.9"
services:
  rabbitmq:
    container_name: RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=${DEFAULT_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${DEFAULT_PASSWORD}
    image: ${RABBITMQ_IMAGE}
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: ${RESTART_MODE}
