services:
  mysql:
    container_name: mysql
    image: mysql:8.0.27
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_shared_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -u root -p$$MYSQL_ROOT_PASSWORD || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:


networks:
  mysql_shared_network:
    name: mysql_shared_network
    driver: bridge
