services:
  mongo:
    container_name: mongodb
    image: mongo:8.0.9
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mongodb_shared_network

volumes:
  mongo_data:


networks:
  mongodb_shared_network:
    name: mongodb_shared_network
    driver: bridge
