services:
  # ----------mongodb----------
  mongo:
    command: mongod
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DEFAULT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DEFAULT_PASSWORD}
    image: ${MONGO_IMAGE}
    ports:
      - 27017:27017
    restart: ${RESTART_MODE}
    volumes:
      - ./mongo_data:/data/db