services:
  vault:
    container_name: vault
    image: hashicorp/vault:1.19.0
    ports:
      - "8200:8200"
    restart: unless-stopped
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      # - VAULT_ADDR=http://0.0.0.0:8200              ## for production
    volumes:
      - vault_data:/vault/data
      # - ./config/vault.hcl:/vault/config/vault.hcl  ## for production
    networks:
      - postgres_shared_network
    # cap_add:                                        ## for production
    #   - IPC_LOCK
    # command: vault server -config=/vault/config/vault.hcl
    # user: root

volumes:
  vault_data:


networks:
  postgres_shared_network:
    external: true
