version: "3.9"

services:
  minio:
    container_name: minio-server
    image: docker.io/bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    privileged: true  
    volumes:
      - '/home/uni/minio_data:/data'
    restart:
      always

    environment:
      MINIO_ROOT_USER: 'admin'
      MINIO_ROOT_PASSWORD: 'minio@1024'
