# - NOTE: not tested yet
services:
  # ----------- kafka -------------
  kafka:
    container_name: Kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    image: ${KAFKA_IMAGE}
    ports:
      - 19092:19092
      - 29092:29092
    restart: ${RESTART_MODE}
    volumes:  
      - ./kafka_data:/data/db
  # ---------- kafka_ui ------------
  kafka_ui:
    container_name: Kafka_UI
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_ZOOKEEPER: localhost:12181
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
    image: ${KAFKA_UI_IMAGE}
    ports:
      - 19093:8080
    restart: ${RESTART_MODE}
  # ---------- zookeeper ------------
  zookeeper:
    container_name: ZooKeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
    hostname: zookeeper
    image: ${ZOOKEEPER_IMAGE}
    ports:
      - 12181:12181
    restart: ${RESTART_MODE}
    volumes:
      - ./zookeeper_data:/data/db