version: "3.9"
services:
  mysql:
    container_name: mysql
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_USER=${DEFAULT_USERNAME}
      - MYSQL_PASSWORD=${DEFAULT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
    image: ${MYSQL_IMAGE}
    ports:
      - "3306:3306"
    restart: ${RESTART_MODE}
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    external: true
