version: "3.9"
services:
  elasticsearch:
    container_name: Elasticsearch
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    image: ${ELASTICSEARCH_IMAGE}
    networks:
      - ek-net
    ports:
      - 9200:9200
      - 9300:9300
    restart: ${RESTART_MODE}
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data
      - ./elastic_config:/usr/share/elasticsearch/config

  kibana:
    container_name: Kibana
    image: ${KIBANA_IMAGE}
    environment:
      - ELASTICSEARCH_HOSTS=http://Elasticsearch:9200
      - "discovery.type=single-node"
    networks:
      - ek-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    restart: ${RESTART_MODE}

networks:
  ek-net:
    driver: bridge
