services:
  # ----------consul----------
  consul:
    container_name: consul
    # environment:
    # - CONSUL_BIND_INTERFACE=eth0
    image: ${CONSUL_IMAGE}
    # networks:
    # - consul
    ports:
      - 8500:8500
      - 8600:8600
    restart: ${RESTART_MODE}
    # volumes:
    #  - ./server1.json:/consul/config/server1.json:ro
    #  - ./certs/:/consul/config/certs/:ro
    # # -----consul-client-------
    # consul-client:
    #   command: "agent"
    #   container_name: consul-client
    #   image: ${CONSUL_IMAGE}
    #   networks:
    #     - consul
    #   restart: ${RESTART_MODE}
    #   volumes:
    #    - ./client.json:/consul/config/client.json:ro
    #    - ./certs/:/consul/config/certs/:ro
    # ----------vault----------
  vault:
    container_name: vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
    image: ${VAULT_IMAGE}
    ports:
      - 8200:8200
    restart: ${RESTART_MODE}
    # ----------networks----------
    # networks:
    # consul:
    # driver: bridge
