version: "3.9"
services:
  consul:
    container_name: Consul
    image: ${CONSUL_IMAGE}
    ports:
      - "8500:8500"
      - "8600:8600"
    restart: ${RESTART_MODE}
    # Uncomment the following lines if custom configurations or certificates are required
    # environment:
    #   - CONSUL_BIND_INTERFACE=eth0
    # volumes:
    #   - ./server1.json:/consul/config/server1.json:ro
    #   - ./certs/:/consul/config/certs/:ro

  vault:
    container_name: Vault
    image: ${VAULT_IMAGE}
    ports:
      - "8200:8200"
    restart: ${RESTART_MODE}
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
    volumes:
      - ./vault_data/data:/vault/data
    # Uncomment if you want Vault to run in dev mode with additional options
    # command: server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200
    # cap_add:
    #   - IPC_LOCK

# Uncomment this section if a custom network is required
# networks:
#   consul:
#     driver: bridge
