version: "3.9"
services:
  consul:
    container_name: Consul
    # environment:
    # - CONSUL_BIND_INTERFACE=eth0
    image: ${CONSUL_IMAGE}
    # networks:
    # - consul
    ports:
      - 8500:8500
      - 8600:8600
    restart: ${RESTART_MODE}
    # volumes:
    #  - ./server1.json:/consul/config/server1.json:ro
    #  - ./certs/:/consul/config/certs/:ro

    # consul-client:
    #   command: "agent"
    #   container_name: consul-client
    #   image: ${CONSUL_IMAGE}
    #   networks:
    #     - consul
    #   restart: ${RESTART_MODE}
    #   volumes:
    #    - ./client.json:/consul/config/client.json:ro
    #    - ./certs/:/consul/config/certs/:ro

  vault:
    container_name: Vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
    image: ${VAULT_IMAGE}
    ports:
      - 8200:8200
    restart: ${RESTART_MODE}
    volumes:
      - ./vault_data/data:/vault/data
    # cap_add:
    #   - IPC_LOCK
    # command: server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200

    # networks:
    # consul:
    # driver: bridge
