services:
  # ----------consul----------
  consul:
    container_name: consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    image: ${CONSUL_IMAGE}
    ports:
      - 8500:8500
      - 8600:8600
    restart: ${RESTART_MODE}
  # ----------vault----------
  vault:
    container_name: vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
    image: ${VAULT_IMAGE}
    ports:
      - 8200:8200
    restart: ${RESTART_MODE}