services:
  minio:
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioAdmin
      - MINIO_ROOT_PASSWORD=minioAdmin
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    networks:
      - minio_net
    ports:
      - 9000:9000
      - 9001:9001
    restart: unless-stopped
    volumes:
      - ~/minio/data:/data

networks:
  minio_net:
