services:
  kafka:
    container_name: kafka
    image: soldevelo/kafka:3.9.0

    environment:
      KAFKA_KRAFT_CLUSTER_ID: my-cluster-id
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_EXTERNAL://:29092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_EXTERNAL://localhost:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

    ports:
      - "29092:29092"

    volumes:
      - kafka_data:/bitnami/kafka/data

    restart: unless-stopped

volumes:
  kafka_data:

networks:
  default:
    external: true
    name: infrastructure
