services:
  camunda:
    container_name: camunda
    image: camunda/camunda-bpm-platform:tomcat-7.21.0
    ports:
      - 26500:26500
    restart: unless-stopped
    volumes:
      - ./camunda_data:/data/db
    networks:
      - mysql_shared_network

networks:
  mysql_shared_network:
    external: true
