services:
  redis:
    container_name: Redis
    image: redis:7.4.2-alpine3.21
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - shared_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  redis_data:


networks:
  shared_network:
    external: true
